// <auto-generated />
namespace Blogging_Times.Posts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _3_Post_work : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_Post_work));
        
        string IMigrationMetadata.Id
        {
            get { return "201805100755085_3_Post_work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
