// <auto-generated />
namespace Blogging_Times.Posts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _5_steps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5_steps));
        
        string IMigrationMetadata.Id
        {
            get { return "201805111746161_5_steps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
